export const HOME_RENDER_POST = "HOME_RENDER_POST";
export const HOME_INCREASE_VIEW_POST = "HOME_INCREASE_VIEW_POST";
export const HOME_GET_CATEGORY = "HOME_GET_CATEGORY";
export const HOME_GET_INFO_PRODUCT = "HOME_GET_INFO_PRODUCT";