export const ACCOUNT_LOGIN = "ACCOUNT_LOGIN" 
export const ACCOUNT_LOGIN_FAIL = "ACCOUNT_LOGIN_FAIL" 
export const ACCOUNT_REGISTER = "ACCOUNT_REGISTER" 
export const ACCOUNT_INFO_USER = "ACCOUNT_INFO_USER" 